//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloodBankEntities : DbContext
    {
        public BloodBankEntities()
            : base("name=BloodBankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BloodTbl> BloodTbls { get; set; }
        public virtual DbSet<CollectTbl> CollectTbls { get; set; }
        public virtual DbSet<DonorTbl> DonorTbls { get; set; }
        public virtual DbSet<EmployeeTbl> EmployeeTbls { get; set; }
        public virtual DbSet<PatientTbl> PatientTbls { get; set; }
        public virtual DbSet<TrasferTbl> TrasferTbls { get; set; }
    }
}
