//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BloodTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BloodTbl()
        {
            this.CollectTbls = new HashSet<CollectTbl>();
            this.TrasferTbls = new HashSet<TrasferTbl>();
        }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Blood Group")]
        public string BGroup { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Number Of Bags")]
        public int BStock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectTbl> CollectTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrasferTbl> TrasferTbls { get; set; }
    }
}
