//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DonorTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonorTbl()
        {
            this.CollectTbls = new HashSet<CollectTbl>();
        }
        [Display(Name = "Serial Number of Donors")]
        public int DNum { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Name")]
        public string DName { get; set; }
        [Required]
        [Display(Name = "Age")]
        public int DAge { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Sex")]
        public string DGender { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        public string DPhone { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string DAddress { get; set; }
        [Required]
        [Display(Name = "Blood Group")]
        public string DBGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectTbl> CollectTbls { get; set; }
    }
}
