//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeTbl
    {
        [Display(Name ="Serial Number")]
        public int EmpNum { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Name")]
        public string EmpId { get; set; }
        [Required]
        [MaxLength(20,ErrorMessage ="Password Is More Than 20 Chracters.")]
        [MinLength(6,ErrorMessage = "Password Is Less Than 6 Chracters.")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string EmpPass { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("EmpPass",ErrorMessage="password not matched!")]
        public string ConfirmEmpPass { get; set; }
    }
}
